### PR TITLE
Bump: Main Package Version

### PR DESCRIPTION
**Pull request by zuhno**
I have updated the version in the main package.(1.3.2 -> 1.3.4, 1.3.3 is already released) Once this PR is merged, I will pull again and push PR(https://github.com/wavezync/vue3-google-signin/pull/61).

One thing I'm curious about is whether it's correct for contributors to update the main package version themselves? It seems like it could be challenging to manage versions with multiple contributors. 🥲

### CODE REVIEW

**Comment by kasvith** [comment]
oops, sorry i had actually missed to bump the version when releasing

**Comment by frasza** [comment]
What is the situation here?

**Comment by kasvith** [comment]
Hi, im doing some internal vite migrations to support new features. Will do
a new release after that

**Comment by kasvith** [comment]
Hey, im doing a new release with bumped up version which uses new vite5 for the development

**Comment by kasvith** [comment]
Released the new version 🚀

**Pull request closed without merging**
