### PR TITLE
fix: Google One Tap callback response error

### PR DESCRIPTION
**Pull request by lzdyes**
#### What is the current behavior?

1. fix: https://github.com/wavezync/vue3-google-signin/issues/79
2. fix: https://github.com/wavezync/vue3-google-signin/pull/80

#### What is the new behavior?

1. Fixed the issue where it always called back to onError. Now it can successfully call back to onSuccess.
3. I modified the CredentialResponse object definition, removed the clientId field, and added the state field. This adjustment was made based on the definition in the official Google documentation: https://developers.google.com/identity/gsi/web/reference/js-reference#CredentialResponse
4. Fixed GoogleSignInButton.vue build type error.

### CODE REVIEW

**Comment by kasvith** [comment]
hi yes, wait i need to update CI to run on PRs

**Comment by kasvith** [comment]
@lzdyes can you update your branch

**Comment by lzdyes** [comment]
@kasvith Could you help release a new npm version?

**Comment by kasvith** [comment]
Hey sure, im afk now

Will release it today

**Comment by kasvith** [comment]
Hi @lzdyes https://github.com/wavezync/vue3-google-signin/releases/tag/v2.0.0 released

**Pull request merged**
